name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Или master, если используете master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Важно для истории коммитов

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install and Build
      run: |
        npm install
        NODE_ENV=production npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        keep_files: false
        enable_jekyll: false  
